import type { Metadata } from "next";
import { Geist, Geist_Mono, KoHo } from "next/font/google";
import { Zalando_Sans } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Header } from "./Header/Header";
import { Footer } from "./Footer/Footer";
import MobileSidebar from "./components/MobileSidebar/MobileSidebar";
import { LoginPanel } from "./components/LoginPanel/LoginPanel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const koho = KoHo({
  subsets: ["latin"],
  style: ["normal", "italic"], // если нужны обе версии
  weight: ["200", "300", "400", "500", "600", "700"], // ВСЕ веса, которые используешь
  variable: "--font-koho",
  display: "swap",
});
export const zalandoSans = Zalando_Sans({
  subsets: ["latin"], // нужные подмножества
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"], // все веса
  style: ["normal", "italic"], // обычный и курсив
  variable: "--font-zalando", // CSS-переменная для удобного использования
  display: "swap", // чтобы шрифт подгружался без FOUT
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Digital Printing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={` antialiased`}>
        <Header />
        {/* <LoginPanel/> */}
        {/* <Sidebar/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
