import type { Metadata } from "next";
import { Geist, Geist_Mono, KoHo } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Header } from "./Header/Header";
import { Footer } from "./Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const koho = KoHo({
  subsets: ["latin"],
  style: ["normal", "italic"],        // если нужны обе версии
  weight: ["200", "300", "400", "500", "600", "700"], // ВСЕ веса, которые используешь
  variable: "--font-koho",
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${koho.variable} antialiased`}
      >
      <Header/>
      {/* <Sidebar/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
